-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(64) NOT NULL,
    password character varying(64) NOT NULL,
    role character varying(64),
    credit double precision NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.toppings;

CREATE TABLE IF NOT EXISTS public.toppings
(
    topping character varying(64) NOT NULL,
    price integer NOT NULL,
    PRIMARY KEY (topping)
);

DROP TABLE IF EXISTS public.bottoms;

CREATE TABLE IF NOT EXISTS public.bottoms
(
    bottom character varying(64) NOT NULL,
    price integer NOT NULL,
    PRIMARY KEY (bottom)
);

DROP TABLE IF EXISTS public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    topping character varying(64) NOT NULL,
    bottom character varying(64) NOT NULL,
    amount integer NOT NULL,
    is_processed boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (topping)
    REFERENCES public.toppings (topping) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (bottom)
    REFERENCES public.bottoms (bottom) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;